### ISSUE TITLE
Having difficulty running module with MMM-GoogleAssistant

### ISSUE THREAD

**Issue by LuckyToes** [EbenKouao/MMM-SmartTouch#2]
Hi,

Your module is awesome. 

I'm unfortunately having an issue to get the IR touch to recognize input while I run the MMM-GoogleAssistant module (It works if I disable the module). Unsure where to go from here, and hoping someone might have an idea how to help me out.

I'm a bit of a beginner but can try to provide whatever additional info that's needed.

Thanks.

**Comment by EbenKouao** [comment]
Hi @LuckyToes,

(Talk about a late reply)
Hope you solved your issue, if not do you mind explaining exactly what input it's not recognizing.
Also, the MMM-GoogleAssistant isn't a module I developed. 

May be worth posting here: https://github.com/bugsounet/MMM-GoogleAssistant.

Good luck.
