### ISSUE TITLE
Starting magic mirror laods the Power/Restart buttons a few inches from the right-edge of the screen

### ISSUE THREAD

**Issue by MichaelDally** [EbenKouao/MMM-SmartTouch#4]
Great module!

When install the module and run MM with npm start, the side bar item is displayed on the screen but does not appear to be attached to the side of the screen
![2020-09-27-120904_1920x1080_scrot](https://user-images.githubusercontent.com/6410138/94363476-48c94880-00ba-11eb-820e-366a66566cb2.png)

**Comment by fordsteve** [comment]
Mine is the same. I looked for ages in config/css files and couldn’t find where to alter the size.

**Comment by EbenKouao** [comment]
HI @MichaelDally @fordsteve,

Nice backdrop.

I see. It appears your monitor is large enough to show the side menu without it being activated. 

Open the MMM-SmartTouch/css/mmm-smarttouch.css Alter the CSS line 121: 
transform: translateX(600%); 
to say... transform: translateX(750%); 
What this will do is move the side menu of the screen (from the right). 

For now, you can experiment with the parameter values to best suit your monitor size. Likewise, you could alter line 133 to alter where you would like the side menu to be position once activated.

Let me know if this sorts it.
If you/anyone improves the module to scale based on monitor size feel free to commit to the repo.

Cheers.

**Comment by fordsteve** [comment]
Thanks for that, will try when I get chance and update here. 

Steve

Steve Ford
UK Tequila Forum
www.uktequilaforum.co.uk
