### ISSUE TITLE
bottom_bar option needs to be fixed, ill try when i have time

### ISSUE THREAD

**Issue by ghost** [EbenKouao/MMM-SmartTouch#9]
need the bottom_bar option centered because having it in the bottom center makes it inconvenient for certain apps in alot of positions, for now it just sits on the right side which i cant use with carousel

**Comment by EbenKouao** [comment]
Sure, please do pull these changes in when fixed. For now, I'm working on a couple of other projects, so I won't be updating this module for a while. Thanks!
